---

# Install jenv

- name: brew install jEnv
  homebrew:
    name: jenv
    state: present

- name: Creates profile.d directory
  file:
    path: $HOME/profile.d
    state: directory

- name: Basic Template Example
  template:
    src: patch.j2
    dest: $HOME/profile.d/patch.sh

- name: setup jEnv
  shell: . /Users/{{ param_user }}/.bashrc && yes | jenv add {{ detect_java_home.stdout }}
  register: result

- debug:
    msg: "{{ result.stdout }}"

- name: set Java 8 as Global in jEnv
  shell: jenv global 1.8

...
