---

# Install jenv

- name: brew install jEnv
  homebrew:
    name: jenv
    state: present

- name: Generate script to profile.d
  become: yes
  template:
    src: patch.j2
    dest: /Users/{{ param_user }}/profile.d/jenv.sh
    owner: "{{ param_user }}"
    mode: 0755

- name: setup jEnv # noqa 306 Shells that use pipes should set the pipefail option
  shell: . /Users/{{ param_user }}/.bashrc && (yes | jenv add {{ detect_java_home.stdout }})
  register: result

- debug:
    msg: "{{ result.stdout }}"

- name: set Java 8 as Global in jEnv
  shell: jenv global 1.8

...
