---

# Install jenv

- name: brew install jEnv
  homebrew:
    name: jenv
    state: present

- name: Creates profile.d directory
  become: yes
  file:
    path: /Users/{{ param_user }}/profile.d
    state: directory
    owner: "{{ param_user }}"
    mode: 0755

- name: Create patch.sh to profile.d
  become: yes
  template:
    src: patch.j2
    dest: /Users/{{ param_user }}/profile.d/jenv_patch.sh
    owner: "{{ param_user }}"
    mode: 0755

- name: setup jEnv
  become: yes
  shell: . /Users/{{ param_user }}/.bashrc && . /Users/{{ param_user }}/profile.d/jenv_patch.sh && yes | jenv add {{ detect_java_home.stdout }}
  register: result

- debug:
    msg: "{{ result.stdout }}"

- name: set Java 8 as Global in jEnv
  shell: jenv global 1.8

...
