---

# Install jenv

- name: brew install jEnv
  homebrew:
    name: jenv
    state: present

- name: Creates profile.d directory
  file:
    path: /Users/{{ param_user }}/profile.d
    state: directory
    owner: {{ param_user }}
    group: wheel
    mode: 0660

- name: Create patch.sh to profile.d
  template:
    src: patch.j2
    dest: /Users/{{ param_user }}/profile.d/jenv_patch.sh
    owner: {{ param_user }}
    group: wheel
    mode: 0770

- name: setup jEnv
  shell: . /Users/{{ param_user }}/.bashrc && yes | jenv add {{ detect_java_home.stdout }}
  register: result

- debug:
    msg: "{{ result.stdout }}"

- name: set Java 8 as Global in jEnv
  shell: jenv global 1.8

...
