---

# Install jenv

- name: brew install jEnv
  homebrew:
    name: jenv
    state: present

- name: Creates profile.d directory
  file:
    path: $HOME/profile.d
    state: directory

- name: Ensure patch file exists
  copy:
    content: ""
    dest: $HOME/profile.d/patch2.sh
    force: no

- name: Patch .bashrc
  blockinfile:
    path: $HOME/profile.d/patch2.sh
    block: "{{ lookup('template', 'patch.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Android Additions"

- name: setup jEnv
  shell: . /Users/{{ param_user }}/.bashrc && yes | jenv add {{ detect_java_home.stdout }}
  register: result

- debug:
    msg: "{{ result.stdout }}"

- name: set Java 8 as Global in jEnv
  shell: jenv global 1.8

...
