---
- name: "bitrise CLI: download"
  get_url:
    url: https://github.com/bitrise-io/bitrise/releases/download/{{ bitrise_cli_version }}/bitrise-{{ ansible_system }}-x86_64  # yamllint disable-line rule:line-length
    dest: /usr/local/bin/bitrise
    mode: '0755'
    owner: "{{ param_user }}"
    group: wheel
  become: true

- name: "Bitrise CLI - setup"
  shell: bitrise setup
  args:
    executable: /bin/bash

# setup the default StepLib collection to stepman, for a pre-warmed
#  cache for the StepLib
- name: "stepman: init"
  shell: $HOME/.bitrise/tools/stepman setup -c https://github.com/bitrise-io/bitrise-steplib.git
  args:
    executable: /bin/bash

- name: "stepman: update"
  shell: $HOME/.bitrise/tools/stepman update
  args:
    executable: /bin/bash
...
