---
- name: Test if CLI is installed
  shell: bitrise --version
  args:
    executable: /bin/bash
  changed_when: false
  ignore_errors: true
  register: cli_is_installed

- name: Install/Update Bitrise CLI
  include_tasks:
    file: cli-install.yml
  when: >
    cli_is_installed.rc != 0 or
    cli_is_installed.stdout != bitrise_cli_version|string
...
