---
- name: Download den agent
  get_url:
    url: "https://api.github.com/repos/bitrise-io/den/releases/assets/{{ bitrise_den_version }}"
    dest: /var/tmp/bitrise-den-darwin-amd64.zip
    headers:
      Authorization: "token {{ lookup('env', 'GITHUB_ACCESS_TOKEN') }}"
      Accept: "application/octet-stream"
- name: "bitrise DEN: extract"
  unarchive:
    src: /var/tmp/bitrise-den-darwin-amd64.zip
    dest: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/bitrise-den-agent"
    exclude:
      - bitrise-den-cli
      - bitrise-den-server
    owner: "{{ param_user }}"
    mode: '0755'
    group: staff
    remote_src: true
  become: true
