---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#
## Required Environment Variables
## XCODE_INSTALL_USER
## XCODE_INSTALL_PASSWORD
## FASTLANE_SESSION

- hosts: all
  become_method: sudo
  any_errors_fatal: true
  vars:
    param_user: vagrant
    xcode_path: "/Applications/Xcode.app"
  roles:
    - role: profiles
    - role: brew
    - role: brew-repos-fix
    - role: xcode
