---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  become_method: sudo
  any_errors_fatal: true
  vars:
    param_user: vagrant
    bitrise_cli_version: "1.43.0"
  roles:
    - role: profiles
    - role: certs
    - role: java
    - role: jenv
    - role: android
    - role: android-apk-tools
    - role: java-tools
    - role: flutter
