---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  become_method: sudo
  any_errors_fatal: true
  vars:
    - param_user: vagrant
    - XCODE_INSTALL_USER: <XXXX>
    - XCODE_INSTALL_PASSWORD: <XXXX>
  roles:
    - role: profiles
    - role: brew
    - role: brew-repos-fix
    - role: tmp-setup
    - role: ruby
    - role: install-xcode
