---

# Ansible playbook to install Java 8 and Android tools on OSX

- hosts: all
  remote_user: vagrant
  become_method: sudo
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
  roles:
    - java
    - jenv
    - android
    - tools
    - patch_bashrc
    - flutter

...
