---

# Ansible playbook to install Java 8 and Android tools on OSX

- hosts: all
  remote_user: vagrant
  become_method: sudo
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
    - android_home: /usr/local/share/android-sdk
    - android_ndk_home: /opt/android-ndk
    - android_ndk_version: r16b
    - android_ndk_source: https://dl.google.com/android/repository/android-ndk-{{ android_ndk_version }}-darwin-x86_64.zip
  roles:
    - java
    - jenv
    - android
    - tools
    - patch_bashrc
    - flutter

...
