---

# Ansible playbook to install Java 8 and Android tools on OSX

- hosts: all
  remote_user: vagrant
  become_method: sudo
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
    - android_home: /usr/local/share/android-sdk
    - android_ndk_home: /opt/android-ndk
    - android_ndk_version: r16b
    - android_ndk_source: https://dl.google.com/android/repository/android-ndk-{{ android_ndk_version }}-darwin-x86_64.zip
    - patch_marker: "Java8 & Android Additions"
  roles:
    - java
    - android
    - tools
    - patch_bashrc

  # This needs to be done after jEnv is installed (tools role) and .bashrc is patched (patch_bashrc role)
  tasks:
    - name: setup jEnv
      shell: . /Users/{{ param_user }}/.bashrc && yes | jenv add {{ detect_java_home.stdout }}
      register: result
    - debug:
        msg: "{{ result.stdout }}"

    - name: set Java 8 as Global in jEnv
      shell: jenv global 1.8

...
