---
- hosts: all
  remote_user: vagrant
  become_method: sudo
  any_errors_fatal: True
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
    - ansible_ssh_private_key_file: "~/.ssh/build_id_ed25519"
  roles:
    - role: security-bypass
...
