---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  become_method: sudo
  any_errors_fatal: True
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
    - bitrise_cli_version: "{{ lookup('file', '/Users/vagrant/git/cli_version.txt') }}"
  roles:
    - role: ssh-setup
    - role: profiles
    - role: brew
    - role: tmp-setup
    - role: ruby
