---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  become_method: sudo
  any_errors_fatal: true
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
    - bitrise_cli_version: "{{ lookup('file', '/Users/vagrant/git/cli_version.txt') }}"
  roles:
    - role: profiles
    - role: certs
    - role: ssh-setup
    - role: brew-repos-fix
    - role: weekly-update-shared
    - role: go
    - role: bitrise-cli
    - role: remote-access
    - role: java
    - role: jenv
    - role: android
    - role: android-apk-tools
    - role: xamarin
      when: is_allow_weekly_xamarin_provision | default("no") | string  == "yes"
    - role: java-tools
      tags: java-android
    - role: flutter
