---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
  tasks:
    #
    # Required param checks


    #
    # Setup profiles

    # The main Xamarin profile, includes
    #  the Xamarin specific environments
    - name: setup xamarin_profile
      copy: src=profiles/xamarin_profile
        dest="/Users/{{ param_user }}/.profiles/xamarin_profile"
        owner="{{ param_user }}"
        mode=0600

    # Java 8 install
    # We need Java 8 because sdkmanager doesn't support newer Java versions (yet)
    # Also we need to manually call launchctl because otherwise it breaks the brew uninstall task
    - name: Stop Java's Helper-Tool
      shell: launchctl remove com.oracle.java.Helper-Tool
      become: yes
      ignore_errors: yes
    - name: Stop Java's Java-Updater
      shell: launchctl remove com.oracle.java.Java-Updater
      become: yes
      ignore_errors: yes
    - name: brew uninstall latest java
      homebrew_cask: name=java state=absent
    - name: brew tap caskroom/versions
      homebrew_tap: name='caskroom/versions' state=present
    - name: brew install java8
      homebrew_cask: name=java8 state=present

    # ------------------------------------------------------
    # --- Install Android SDKs and other build packages

    # Other tools and resources of Android SDK
    #  you should only install the packages you need!
    # To get a full list of available options you can use:
    #  android list sdk --no-ui --all --extended
    # (!!!) Only install one package at a time, as "echo y" will only work for one license!
    #       If you don't do it this way you might get "Unknown response" in the logs,
    #         but the android SDK tool **won't** fail, it'll just **NOT** install the package.
    - name: install platform-tools
      shell: echo "y\ny\ny\ny\ny" | sdkmanager "emulator" "tools" "platform-tools"

    # SDKs
    # Please keep these in descending order!
    - name: install android-27
      shell: echo y | sdkmanager "platforms;android-27"
    - name: install android-26
      shell: echo y | sdkmanager "platforms;android-26"
    - name: install android-25
      shell: echo y | sdkmanager "platforms;android-25"
    - name: install android-24
      shell: echo y | sdkmanager "platforms;android-24"
    - name: install android-23
      shell: echo y | sdkmanager "platforms;android-23"
    - name: install android-22
      shell: echo y | sdkmanager "platforms;android-22"
    - name: install android-21
      shell: echo y | sdkmanager "platforms;android-21"
    - name: install android-20
      shell: echo y | sdkmanager "platforms;android-20"
    - name: install android-19
      shell: echo y | sdkmanager "platforms;android-19"
    - name: install android-17
      shell: echo y | sdkmanager "platforms;android-17"
    - name: install android-15
      shell: echo y | sdkmanager "platforms;android-15"
    - name: install android-10
      shell: echo y | sdkmanager "platforms;android-10"

    # build tools
    # Please keep these in descending order!
    - name: install build-tools-26.0.2
      shell: echo y | sdkmanager "build-tools;26.0.2"
    - name: install build-tools-25.0.2
      shell: echo y | sdkmanager "build-tools;25.0.2"
    - name: install build-tools-25.0.1
      shell: echo y | sdkmanager "build-tools;25.0.1"
    - name: install build-tools-25.0.0
      shell: echo y | sdkmanager "build-tools;25.0.0"
    - name: install build-tools-24.0.3
      shell: echo y | sdkmanager "build-tools;24.0.3"
    - name: install build-tools-24.0.2
      shell: echo y | sdkmanager "build-tools;24.0.2"
    - name: install build-tools-24.0.1
      shell: echo y | sdkmanager "build-tools;24.0.1"
    - name: install build-tools-24.0.0
      shell: echo y | sdkmanager "build-tools;24.0.0"
    - name: install build-tools-23.0.3
      shell: echo y | sdkmanager "build-tools;23.0.3"
    - name: install build-tools-23.0.2
      shell: echo y | sdkmanager "build-tools;23.0.2"
    - name: install build-tools-23.0.1
      shell: echo y | sdkmanager "build-tools;23.0.1"
    - name: install build-tools-22.0.1
      shell: echo y | sdkmanager "build-tools;22.0.1"
    - name: install build-tools-21.1.2
      shell: echo y | sdkmanager "build-tools;21.1.2"
    - name: install build-tools-20.0.0
      shell: echo y | sdkmanager "build-tools;20.0.0"
    - name: install build-tools-19.1.0
      shell: echo y | sdkmanager "build-tools;19.1.0"
    - name: install build-tools-17.0.0
      shell: echo y | sdkmanager "build-tools;17.0.0"

    # Android System Images, for emulators
    # Please keep these in descending order!
    - name: install sys-img-armeabi-v7a-android-24
      shell: echo y | sdkmanager "system-images;android-24;default;armeabi-v7a"
    - name: install sys-img-armeabi-v7a-android-22
      shell: echo y | sdkmanager "system-images;android-22;default;armeabi-v7a"
    - name: install sys-img-armeabi-v7a-android-21
      shell: echo y | sdkmanager "system-images;android-21;default;armeabi-v7a"
    - name: install sys-img-armeabi-v7a-android-19
      shell: echo y | sdkmanager "system-images;android-19;default;armeabi-v7a"
    - name: install sys-img-armeabi-v7a-android-17
      shell: echo y | sdkmanager "system-images;android-17;default;armeabi-v7a"
    - name: install sys-img-armeabi-v7a-android-15
      shell: echo y | sdkmanager "system-images;android-15;default;armeabi-v7a"

    # Extras
    - name: install extra-android-m2repository
      shell: echo y | sdkmanager "extras;android;m2repository"
    - name: install extra-google-m2repository
      shell: echo y | sdkmanager "extras;google;m2repository"
    - name: install extra-google-google_play_services
      shell: echo y | sdkmanager "extras;google;google_play_services"

    # google apis
    # Please keep these in descending order!
    - name: install addon-google_apis-google-23
      shell: echo y | sdkmanager "add-ons;addon-google_apis-google-23"
    - name: install addon-google_apis-google-22
      shell: echo y | sdkmanager "add-ons;addon-google_apis-google-22"
    - name: install addon-google_apis-google-21
      shell: echo y | sdkmanager "add-ons;addon-google_apis-google-21"

    #
    # Install debug.keystore
    # $HOME/.local/share/Xamarin/Mono for Android/debug.keystore
    - name: "ensure Xamarin debug.keystore dir exists"
      file: path="/Users/{{ param_user }}/.local/share/Xamarin/Mono for Android"
        state=directory
        owner="{{ param_user }}"
        mode=0755
    - name: install debug.keystore
      copy: src=xamarin/debug.keystore
        dest="/Users/{{ param_user }}/.local/share/Xamarin/Mono for Android/debug.keystore"
        owner="{{ param_user }}"
        mode=0644

    #
    # Setup Bitrise specific folders
    #
    # Setup the base folders / paths, referenced by ~/.profiles/xamarin_profile
    # These folders will be created in the HOME directory.
    - name: Create bitrise xamarin specific dirs
      file: path="/Users/{{ param_user }}/{{ item.fold_path }}"
        state=directory
        owner="{{ param_user }}"
      with_items:
        # Xamarin tools
        - { fold_path: 'bitrise/xamarin' }

    - name: sync xamarin tools from the provisioning repo
      synchronize: src=xamarin/ dest="/Users/{{ param_user }}/bitrise/xamarin/"

    # Final debug prints
    - debug: msg="---> Finished with automatic stuff - but here's some things you have to do manually:"
    - debug: msg=" (!) After you finished with the preparations RESTART the machine!"
    - debug: msg=" (!) Don't forget to remove the VM snapshots (if you used snapshots) before packaging!"
    - debug: msg="---> Finished"
