---
- name: Remove all (non default) gems
  script: ruby_cleanup.sh
  register: rubycleanupout
  ignore_errors: true
  changed_when: "'Clean up complete' in rubycleanupout.stdout"

- name: Install gem packages
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: "$HOME/.rbenv/shims/gem"
    user_install: false
  with_items:
    - "{{ gem_packages }}"

# GEMs: Cocoapods setup
- name: pod setup
  shell: bash -l -c "pod setup"
  retries: 3
  when: is_incremental_setup|default(false) == false
