---
- name: Remove previous android installations
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ old_android_installs }}"

- name: Prepare Xamarin Android dirs
  file:
    path: "$HOME/{{ item.path }}"
    state: directory
    recurse: true
    owner: "{{ param_user }}"
    mode: "0755"
  with_items:
    - "{{ xamarin_folders }}"

- name: Install Xamarin files
  copy:
    src: "{{ item.name }}"
    dest: "$HOME/{{ item.dest }}"
    owner: "{{ param_user }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ xamarin_files }}"

- name: unarchive xamarin tools
  unarchive:
    src: bitrise/xamarin/xamarin.zip
    dest: "$HOME/bitrise/"
    owner: "{{ param_user }}"
    remote_src: true
