---
- name: Install xcode-install
  gem:
    name: xcode-install
    user_install: false
    executable: "$HOME/.rbenv/shims/gem"

- name: Install xcode version based on xcode_version variable, it could take a while. About an hour, so be patient.
  shell: bash -l -c "xcversion install '{{ xcode_version }}'"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
    FASTLANE_SESSION: "{{ FASTLANE_SESSION | b64decode }}"

# noqa 306 Shells that use pipes should set the pipefail option
- name: Switch to Xcode stable, the default Xcode for building
  shell: bash -l -c 'xcode-select --switch "/Applications/$(ls /Applications | grep Xcode)"'
  become: true

- name: Enable accessibility to xcode
  script: enable_accessibility.sh '{{ ansible_distribution_version }}'
  become: true
