---

# Patch .bashrc

- name: Creates profile.d directory
  file:
    path: $HOME/profile.d
    state: directory

- name: Basic Template Example
  template:
    src: patch.j2
    dest: $HOME/profile.d/patch.sh

...
