---

# Patch .bashrc

- name: Creates profile.d directory
  file:
    path: $HOME/profile.d
    state: directory

- name: Ensure patch file exists
  copy:
    content: ""
    dest: $HOME/profile.d/patch2.sh
    force: no

- name: Patch .bashrc
  blockinfile:
    path: $HOME/profile.d/patch2.sh
    block: "{{ lookup('template', 'patch.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Android Additions"

...
