---
- name: load distribution specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_os_family }}.yml'
      - default.yml

- name: ensure .ssh folder is ok
  become: true
  file:
    path: /{{ home.path }}/{{ param_user }}/.ssh
    state: directory
    owner: "{{ param_user }}"
    mode: "0700"

# Disable every non SSH key based setup option
# allow only SSH key based SSH login
- name: sshd_config settings
  become: true
  template:
    src: templates/etc/ssh/sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    owner: root
    mode: "0644"
    validate: '/usr/sbin/sshd -t -f %s'
    backup: true

- name: ssh connection config (user specific)
  copy:
    src: files/ssh-config
    dest: "/{{ home.path }}/{{ param_user }}/.ssh/config"
    owner: "{{ param_user }}"
    mode: "0600"
