---
- name: Create ANDROID_NDK_HOME directory
  become: true
  file:
    path: "{{ android_ndk_home }}"
    state: directory
    owner: "{{ param_user }}"
    mode: 0770
    recurse: true

- name: Download and unzip Android NDK
  become: true
  unarchive:
    src: "{{ android_ndk_source }}"
    dest: "{{ android_ndk_home }}"
    owner: "{{ param_user }}"
    mode: 0770
    remote_src: true

- name: Create profile.d directory
  file:
    path: "{{ ansible_env.HOME }}/profile.d"
    state: directory
    owner: "{{ param_user }}"

- name: Generate script to profile.d
  become: true
  template:
    src: patch.j2
    dest: "{{ ansible_env.HOME }}/profile.d/android.sh"
    owner: "{{ param_user }}"
    mode: 0755

- name: ensure android directory exists
  become: true
  file:
    dest: "{{ android_home }}/cmdline-tools/"
    state: directory

- name: Download and extract command-line tools for Android
  become: true
  unarchive:
    src: https://dl.google.com/android/repository/commandlinetools-mac-{{ android_cmdline_tools_version }}_latest.zip
    dest: "{{ android_home }}/cmdline-tools/"
    remote_src: true

- name: Touch repositories.cfg
  copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.android/repositories.cfg"
    force: false
    mode: "0777"

- name: Install Android packages with SDK Manager
  become: true
  environment:
    PATH: "{{ android_home }}/tools/bin:{{ android_home }}/cmdline-tools/tools/bin:{{ ansible_env.PATH }}"
  shell: "(echo y | sdkmanager --verbose '{{ item }}') || (echo y | sdkmanager --verbose '{{ item }}')"  # noqa 204 306
  loop:
    - "emulator"
    - "tools"
    - "platform-tools"
    - "platforms;android-29"
    - "platforms;android-28"
    - "platforms;android-27"
    - "platforms;android-26"
    - "platforms;android-25"
    - "platforms;android-24"
    - "platforms;android-23"
    - "platforms;android-22"
    - "platforms;android-21"
    - "platforms;android-19"
    - "platforms;android-17"
    - "platforms;android-15"
    - "build-tools;29.0.3"
    - "build-tools;29.0.2"
    - "build-tools;29.0.1"
    - "build-tools;29.0.0"
    - "build-tools;28.0.3"
    - "build-tools;28.0.2"
    - "build-tools;28.0.1"
    - "build-tools;28.0.0"
    - "build-tools;27.0.3"
    - "build-tools;27.0.2"
    - "build-tools;27.0.1"
    - "build-tools;27.0.0"
    - "build-tools;26.0.2"
    - "build-tools;26.0.1"
    - "build-tools;25.0.3"
    - "build-tools;24.0.3"
    - "build-tools;23.0.3"
    - "build-tools;22.0.1"
    - "build-tools;21.1.2"
    - "build-tools;19.1.0"
    - "build-tools;17.0.0"
    - "system-images;android-29;google_apis;x86"
    - "system-images;android-28;google_apis;x86_64"
    - "system-images;android-26;google_apis;x86"
    - "extras;android;m2repository"
    - "extras;google;m2repository"
    - "extras;google;google_play_services"
    - "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.1"
    - "add-ons;addon-google_apis-google-23"
    - "add-ons;addon-google_apis-google-22"
    - "add-ons;addon-google_apis-google-21"

...
