---

# Install Android SDKs and other build packages

- name: Create ANDROID_HOME directory
  become: yes
  file:
    path: "{{ android_home }}"
    state: directory
    owner: "{{ param_user }}"
    mode : 0770
    recurse: yes

- name: Download Android SDK tools
  become: yes
  get_url:
    url: "{{ android_sdk_source }}"
    dest: /opt/sdk-tools-darwin.zip
    mode: 0660

- name: Unzip Android SDK tools
  become: yes
  unarchive:
    src: /opt/sdk-tools-darwin.zip
    dest: "{{ android_home }}"
    owner: "{{ param_user }}"
    mode: 0770
    remote_src: yes

- name: Remove Android SDK zip file
  become: yes
  file:
    state: absent
    path: /opt/sdk-tools-darwin.zip

- name: Install Android packages with SDK Manager
  become: yes
  environment:
    PATH: "{{ android_home }}/tools/bin:{{ ansible_env.PATH }}"
  shell: "(echo y | sdkmanager '{{ item }}') || (echo y | sdkmanager '{{ item }}')"
  loop:
    - "emulator"
    - "tools"
    - "platform-tools"
    - "platforms;android-28"
    - "platforms;android-27"
    - "platforms;android-26"
    - "platforms;android-25"
    - "platforms;android-24"
    - "platforms;android-23"
    - "platforms;android-22"
    - "platforms;android-21"
    - "platforms;android-19"
    - "platforms;android-17"
    - "platforms;android-15"
    - "build-tools;28.0.3"
    - "build-tools;28.0.2"
    - "build-tools;28.0.1"
    - "build-tools;28.0.0"
    - "build-tools;27.0.3"
    - "build-tools;27.0.2"
    - "build-tools;27.0.1"
    - "build-tools;27.0.0"
    - "build-tools;26.0.2"
    - "build-tools;26.0.1"
    - "build-tools;25.0.3"
    - "build-tools;24.0.3"
    - "build-tools;23.0.3"
    - "build-tools;22.0.1"
    - "build-tools;21.1.2"
    - "build-tools;19.1.0"
    - "build-tools;17.0.0"
    - "system-images;android-28;google_apis;x86"
    - "system-images;android-26;google_apis;x86"
    - "system-images;android-25;google_apis;armeabi-v7a"
    - "system-images;android-24;default;armeabi-v7a"
    - "system-images;android-22;default;armeabi-v7a"
    - "system-images;android-19;default;armeabi-v7a"
    - "extras;android;m2repository"
    - "extras;google;m2repository"
    - "extras;google;google_play_services"
    - "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.1"
    - "add-ons;addon-google_apis-google-23"
    - "add-ons;addon-google_apis-google-22"
    - "add-ons;addon-google_apis-google-21"

# Install Android NDK

- name: Create ANDROID_NDK_HOME directory
  become: yes
  file:
    path: "{{ android_ndk_home }}"
    state: directory
    owner: "{{ param_user }}"
    mode : 0770
    recurse: yes

- name: Download Android NDK
  become: yes
  get_url:
    url: "{{ android_ndk_source }}"
    dest: /opt/android-ndk-darwin.zip
    mode: 0660

- name: Unzip Android NDK
  become: yes
  unarchive:
    src: /opt/android-ndk-darwin.zip
    dest: "{{ android_ndk_home }}"
    owner: "{{ param_user }}"
    mode: 0770
    remote_src: yes

- name: Remove Android NDK zip file
  become: yes
  file:
    state: absent
    path: /opt/android-ndk-darwin.zip

...