---
- name: Create ANDROID_NDK_HOME directory
  become: true
  file:
    path: "{{ android_ndk_home }}"
    state: directory
    owner: "{{ param_user }}"
    mode: "0770"
    recurse: true

- name: Download and unzip Android NDK
  become: true
  unarchive:
    src: "{{ android_ndk_source }}"
    dest: "{{ android_ndk_home }}"
    owner: "{{ param_user }}"
    mode: "0770"
    remote_src: true

- name: Create profile.d directory
  file:
    path: "{{ ansible_env.HOME }}/profile.d"
    state: directory
    owner: "{{ param_user }}"

- name: Generate script to profile.d
  become: true
  template:
    src: patch.j2
    dest: "{{ ansible_env.HOME }}/profile.d/android.sh"
    owner: "{{ param_user }}"
    mode: "0755"

- name: ensure android directory exists
  become: true
  file:
    dest: "{{ android_home }}/cmdline-tools/"
    state: directory
    mode: "0755"

- name: Download and extract command-line tools for Android
  become: true
  unarchive:
    src: "{{ android_cmdline_tools_source }}"
    dest: "{{ android_home }}/cmdline-tools/"
    remote_src: true

- name: Ensure .android directory exists
  file:
    dest: "{{ ansible_env.HOME }}/.android/"
    state: directory

- name: Touch repositories.cfg
  copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.android/repositories.cfg"
    force: false
    mode: "0777"

- name: Install SDKs
  include_tasks: roles/android/tasks/sdk-install.yml
  with_items:
    - "{{ sdkmanagerpackages }}"
  loop_control:
    loop_var: sdk

- name: Recursively change ownership of ANDROID_HOME on Xcode
  become: true
  file:
    path: "{{ android_home }}"
    recurse: true
    owner: "{{ param_user }}"
    group: staff
    mode: '0755'

- name: Recursively change ownership of ANDROID_HOME on vs4mac
  become: true
  file:
    path: "$HOME/Library/Developer/Xamarin/android-sdk-macosx"
    recurse: true
    owner: "{{ param_user }}"
    group: staff
    mode: '0755'
...
