---

# Install Android SDKs and other build packages

- name: brew install android-sdk
  homebrew_cask:
    name: android-sdk
    state: present

# Install Android NDK

- name: Create ANDROID_NDK_HOME directory
  become: true
  file:
    path: "{{ android_ndk_home }}"
    state: directory
    owner: "{{ param_user }}"
    mode: 0770
    recurse: true

- name: Download Android NDK
  become: true
  get_url:
    url: "{{ android_ndk_source }}"
    dest: /opt/android-ndk-darwin.zip
    mode: 0660

- name: Unzip Android NDK
  become: true
  unarchive:
    src: /opt/android-ndk-darwin.zip
    dest: "{{ android_ndk_home }}"
    owner: "{{ param_user }}"
    mode: 0770
    remote_src: true

- name: Remove Android NDK zip file
  become: true
  file:
    state: absent
    path: /opt/android-ndk-darwin.zip

- name: Generate script to profile.d
  become: true
  template:
    src: patch.j2
    dest: /Users/{{ param_user }}/profile.d/android.sh
    owner: "{{ param_user }}"
    mode: 0755

...
