---
- name: Add vagrant user
  user:
    name: vagrant
    comment: default user on bitrise
    group: staff
    password: vagrant
    groups: everyone, localaccounts, _appserverusr, admin, _appserveradm, _lpadmin, com.apple.access_screensharing, com.apple.sharepoint.group.1, _appstore, _lpoperator, _developer, _analyticsusers, com.apple.access_ftp, com.apple.access_ssh, com.apple.access_remote_ae
