---
- name: remove apt python packages
  apt:
    name: ['python', 'python-dev', 'python-pip']
    state: absent
  become: true

- name: remove bin
  file:
    path: "/home/linuxbrew/.linuxbrew/bin/python3"
    state: absent
  become: true
