xcode_version: "11.7"
simulators:
  - 'iOS 13.5'
  - 'iOS 13.4'
  - 'iOS 13.3'
  - 'iOS 13.2'
  - 'iOS 13.1'
  - 'iOS 13.0'
  - 'watchOS 6.0'
  - 'watchOS 6.1.1'
  - 'tvOS 13.3'
  - 'tvOS 13.2'
  - 'tvOS 13.0'
