---
- name: Download flutter from stable channel
  unarchive:
    src: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_{{ flutter_version }}-stable.zip
    dest: "{{ flutter_home }}"
    mode: "0770"
    remote_src: yes
    owner: vagrant
    group: admin
  become: yes

- name: Generate script to profile.d
  become: yes
  template:
    src: patch.j2
    dest: /Users/{{ param_user }}/profile.d/flutter.sh
    owner: "{{ param_user }}"
    mode: "0755"

- name: Run flutter precache
  shell: bash -l -c "{{ flutter_home }}/flutter/bin/flutter precache"

- name: Run flutter doctor
  shell: bash -l -c "{{ flutter_home }}/flutter/bin/flutter doctor"
...
