---
- name: Download flutter from stable channel
  unarchive:
    src: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v{{ flutter_version }}-stable.zip
    dest: "{{ flutter_home }}"
    mode: 0770
    remote_src: yes
    owner: vagrant
    group: admin
  become: yes

- name: Flutter patch .bashrc
  become: yes
  blockinfile:
    insertbefore: "keep a newline"
    path: /Users/{{ param_user }}/.bashrc
    block: "{{ lookup('template', 'patch.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Flutter settings"

- name: Flutter final newline in bashrc
  become: yes
  lineinfile:
    insertbefore: "keep a newline"
    path: /Users/{{ param_user }}/.bashrc
    line: ""

- name: Run flutter precache
  shell: bash -l -c "{{ flutter_home }}/flutter/bin/flutter precache"

- name: Run flutter doctor
  shell: bash -l -c "{{ flutter_home }}/flutter/bin/flutter doctor"
...
