---
- name: Create .profile files
  become: true
  ansible.builtin.template:
    src: .profile.j2
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ param_user }}"
    mode: "0755"
  with_items:
    - '.profile'
    - '.zprofile'

# these 2 steps might be erroneous anyways due to lack of proper paths
- name: Is flutter available?
  shell: bash -l -c "flutter --version"
  ignore_errors: true
  register: is_flutter_available
  changed_when: false

- name: Remove old flutter
  become: true
  file:
    path: "/usr/local/flutter"
    state: absent

- name: Is FVM available?
  shell: bash -l -c "{{ BREW_HOME }}/fvm --version"
  ignore_errors: true
  register: is_fvm_available
  changed_when: false

- name: Install fvm
  when: is_fvm_available.rc != 0
  block:
  # - name: Tap
  #   shell: bash -l -c "{{ BREW_HOME }}/brew tap leoafarias/fvm"
  - name: Tap
    homebrew_tap:
      name: leoafarias/fvm
      state: present
      path: "{{ BREW_HOME }}"
  - name: Install
    homebrew:
      name: fvm
      state: present
      path: "{{ BREW_HOME }}"

- name: Install Flutter versions
  include_tasks:
    file: flutter.yml
  with_items:
    - "{{ flutter_versions }}"
  loop_control:
    loop_var: flutter_version

- name: Set Flutter 1 as default
  shell: bash -l -c "{{ BREW_HOME }}/fvm global {{ flutter_versions[0] }}"  # complete version is required

- name: Warmup flutter
  block:
  - name: Run flutter precache
    shell: bash -l -c "{{ BREW_HOME }}/fvm flutter precache"

  - name: Run flutter doctor
    shell: bash -l -c "{{ BREW_HOME }}/fvm flutter doctor"
...
