---
- name: brew install java
  homebrew_cask:
    name: java
    state: present
- name: brew install formulas
  homebrew:
    name: "{{ item.name }}"
    state: present
    update_homebrew: true
  with_items:
    - "{{ brew_packages }}"
