---
- name: load simulator versions
  include_vars: "{{ xcode_version }}.yml"

- name: Install simulators
  include: install.yml
  with_items:
    - "{{ simulators }}"
  loop_control:
    loop_var: item

- name: xcrun simctl list
  shell: bash -l -c "xcrun simctl list"
  become: true

- name: Cleanup cached downloads
  shell: bash -l -c "xcversion cleanup"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
