---
- name: Install curl
  package:
    name: curl
    state: present
    update_cache: yes

- name: Install git
  package:
    name: git
    state: present
    update_cache: yes

- name: Check if brew installed
  shell: "source ~/.bash_profile && brew --help"
  register: brew_installed
  changed_when: false
  ignore_errors: true

- name: Run brew installer script
  shell: |
    set -o pipefail
    bash -l -c "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | bash"
  when: brew_installed is failed

- name: Is brew in bash_profile
  shell: "grep brew ~/.bash_profile"
  changed_when: false
  ignore_errors: true
  register: bash_profile

- name: Add brew to PATH. Brew officially supported on linux it is called linuxbrew and for test we use that
  shell: "echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.bash_profile"
  when: ansible_distribution == 'CentOS' and bash_profile is failed

- name: Check if repository for brew core is correct
  shell: "source ~/.bash_profile && grep github.com/bitrise-io/homebrew-core $(brew --repository)/Library/Taps/homebrew/homebrew-core/.git/config"
  changed_when: false
  ignore_errors: true
  register: brew_repository_core_set

- name: Setup brew to use our own fork of homebrew core to ensure versions
  script: setup_brew_core.sh
  when: lookup('env', 'IS_CI') and brew_repository_core_set is failed

- name: Check if repository for brew cask is correct
  shell: "source ~/.bash_profile && grep github.com/bitrise-io/homebrew-cask $(brew --repository)/Library/Taps/homebrew/homebrew-cask/.git/config"
  changed_when: false
  ignore_errors: true
  register: brew_repository_cask_set

- name: Setup brew to use our own fork of homebrew cask to ensure versions
  script: setup_brew_cask.sh
  when: lookup('env', 'IS_CI') and brew_repository_cask_set is failed
