---

# Install additional tools

- name: brew install jEnv
  homebrew:
    name: jenv
    state: present

- name: add JAVA_HOME to jEnv
  shell: yes | jenv add {{ detect_java_home.stdout }}
  register: result
- debug:
    msg: "{{ result.stdout }}"

- name: brew install Ant
  homebrew:
    name: ant
    state: present

- name: brew install Maven
  homebrew:
    name: maven
    state: present

- name: brew install Gradle
  homebrew:
    name: gradle
    state: present

...