---
- name: Copy script with owner and permissions
  copy:
    src: ../_deps/osx-box-bootstrap/system_report.sh
    dest: /tmp/system_report.sh
    owner: vagrant
    mode: '755'

- name: Run System report script
  become: yes
  shell: bash -l -c tmp/system_report.sh
  register: result

- name: Remove script from remote machine
  file:
    state: absent
    path: /tmp/system_report.sh

- debug:
  msg: "{{ result.stdout }}"
...