---
- name: Copy script with owner and permissions
  copy:
    src: ../../../system_report.sh
    dest: /tmp/system_report.sh
    owner: vagrant
    mode: '755'

- name: Run System report script
  ignore_errors: yes
  shell: bash -l -c /tmp/system_report.sh
  register: result

- name: Remove script from remote machine
  file:
    state: absent
    path: /tmp/system_report.sh

- debug:
    msg: "{{ result.stdout }}"
...
