---
- name: Install go
  homebrew:
    name: go@1.15
    state: present
    update_homebrew: true

- name: prepare GOPATH dirs
  file:
    path: "{{ ansible_env.HOME }}/go/{{ item.fold_path }}"
    state: directory
    owner: "{{ param_user }}"
  with_items:
    - { fold_path: 'src' }
    - { fold_path: 'bin' }
    - { fold_path: 'pkg' }
...
