---
- name: Install go
  homebrew:
    name: go@1.15
    state: present
    update_homebrew: true

- name: Test if there is a latest go installed
  shell: brew list | grep -x "go"
  args:
    executable: /bin/bash
  changed_when: false
  ignore_errors: true
  register: latest_is_installed

- name: unlink latest go
  shell: brew unlink go
  args:
    executable: /bin/bash
  when: latest_is_installed.rc == 0

- name: Link go 1.15
  shell: brew link go@1.15
  args:
    executable: /bin/bash

- name: prepare GOPATH dirs
  file:
    path: "{{ ansible_env.HOME }}/go/{{ item.fold_path }}"
    state: directory
    owner: "{{ param_user }}"
  with_items:
    - { fold_path: 'src' }
    - { fold_path: 'bin' }
    - { fold_path: 'pkg' }
...
