---
- name: Check if Go is installed
  shell: /usr/local/bin/go version | awk '{print $3}'
  register: go_installation
  ignore_errors: true
  changed_when: false

- name: Clean up old version if necesary
  file:
    path: "{{ ansible_env.HOME }}/go"
    state: absent
  when: go_installation.stdout != go_version|string

- name: Download Go
  get_url:
    url: https://golang.org/dl/{{ go_version }}.{{ ansible_system | lower }}-amd64.tar.gz
    dest: /tmp/go{{ go_version }}.zip
  when: >
    go_installation.rc != 0 or
    go_installation.stdout != go_version|string

- name: unarchive Go
  unarchive:
    src: /tmp/go{{ go_version }}.zip
    dest: "{{ ansible_env.HOME }}"
    remote_src: true
  when: >
    go_installation.rc != 0 or
    go_installation.stdout != go_version|string

- name: install Go
  file:
    src: "{{ ansible_env.HOME }}/go/bin/go"
    dest: /usr/local/bin/go
    owner: "{{ param_user }}"
    mode: "0755"
    state: link
  become: true
  when: >
    go_installation.rc != 0 or
    go_installation.stdout != go_version|string

- name: prepare GOPATH dirs
  file:
    path: "{{ ansible_env.HOME }}/go/{{ item.fold_path }}"
    state: directory
    owner: "{{ param_user }}"
  with_items:
    - { fold_path: 'src' }
    - { fold_path: 'bin' }
    - { fold_path: 'pkg' }
...
