---
- name: Test if Visual Studio is installed
  shell: bash -l -c "ls /Applications | grep 'Visual Studio'"
  register: vs4mac_is_installed
  changed_when: false
  ignore_errors: true

- name: Install cask vs4mac
  homebrew_cask:
    name: visual-studio
    state: present
  when: vs4mac_is_installed.rc != 0
