---
- name: check if {{ dir }} exists
  stat:
    path: "$HOME/{{ dir.path }}"
  changed_when: false
  ignore_errors: true
  register: is_dir_present

- name: create {{ dir }}
  file:
    path: "$HOME/{{ dir.path }}"
    state: directory
    owner: "{{ param_user }}"
    mode: "{{ dir.mode }}"
  when: not is_dir_present.stat.exists
