---
- name: ensure profile directories are ok
  include_tasks:
    file: directories.yml
  with_items:
    - "{{ directories }}"
  loop_control:
    loop_var: dir

- name: install profiles
  copy:
    src: "{{ item.name }}"
    dest: "$HOME/{{ item.dest }}"
    owner: "{{ param_user }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ profiles }}"
