---
#
# Required param checks
- name: Display is_incremental
  debug:
    msg: " (!) Incremental Setup? {{ is_incremental_setup|default(false) }}"

# Setup the debug log file for custom scripts
#  [!] Collect custom script outputs to ~/Desktop/debug.log, for inspection.
# You can inspect it during setup with $ tail -f ~/Desktop/debug.log
#  custom installer scripts use this debug log file
- name: Setup the debug log file for custom scripts
  file:
    path: /Users/{{ param_user }}/Desktop/debug.log
    state: touch
    owner: "{{ param_user }}"
    mode: "0644"

#
# Add user to sudoers-no-password
#  don't require password for running sudo with this user
- name: "Add user {{ param_user }} to sudoers with no password"
  become: true
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ param_user }} ALL'
    line: '{{ param_user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'

# Enable Developer Mode. Without this Xcode.app might block UI Tests,
# waiting for manual input (password). Since Xcode 9.3 it seems this is
# the only way to accept the permissions required for iOS UI Tests,
# if you only accept it via the GUI that won't persist after an OS reboot,
# but running this command will.
- name: "Enable Developer Mode"
  shell: DevToolsSecurity -enable
  become: true

# Turn off automatic update
- name: Turn off macos automatic software updates
  shell: softwareupdate --schedule off
  become: true

# Turn off APSD
- name: "Turn off apsd - can be a CPU hog"
  shell: launchctl unload -w /System/Library/LaunchDaemons/com.apple.apsd.plist
  become: true

# Turn off Gatekeeper
- name: "Turn off gatekeeper - it will disable the popup of the not appstore downloaded warning"
  shell: spctl --master-disable
  become: true
