---
- name: Create apktools_path directory
  become: true
  file:
    path: "{{ apktools_path }}"
    state: directory
    owner: "{{ param_user }}"
    mode: 0770
    recurse: true
  tags:
    - apktools

- name: Download aapt2
  become: true
  get_url:
    url: "{{ aapt2_source }}"
    dest: /opt/aapt2.zip
    mode: 0660
  tags:
    - apktools

- name: Unzip aapt2
  become: true
  unarchive:
    src: /opt/aapt2.zip
    dest: "{{ apktools_path }}"
    owner: "{{ param_user }}"
    mode: 0770
    remote_src: true
  tags:
    - apktools

- name: Remove aapt2 zip file
  become: true
  file:
    state: absent
    path: /opt/aapt2.zip
  tags:
    - apktools

...
