---
- name: Install xcode-install
  gem:
    name: xcode-install
    user_install: false
    executable: "$HOME/.rbenv/shims/gem"

- name: Install xcode version based on xcode_version variable, it could take a while. About an hour, so be patient.
  shell: bash -l -c "xcversion install '{{ xcode_version }}'"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"

- name: Install xcode simulators
  shell: bash -l -c "xcversion simulators --install='{{ item }}'"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
  with_items:
    - "{{ simulators }}"

- name: Cleanup cached downloads
  shell: bash -l -c "xcversion cleanup"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"

- name: Prepare testapps directories
  become: true
  file:
    path: /opt/bitrise/testapps
    state: directory
    owner: "{{ param_user }}"
    group: staff
    mode: '0755'

# instruments is deprecated -> xcrun used instead, but it writes to stderr for some reason hence: 2>&1 >/dev/null
# Sometimes on the first run xcrun xctrace list devices will not report the devices (experience from doing it manually), hence the retry.
- name: Get iOS simulator ID  # noqa 306
  shell: >
    bash -l -c "set -o pipefail && xcrun xctrace list devices 2>&1 >/dev/null | grep iPhone | head -1 | awk -F '[: ]' '{print \$4}' | awk -F'[()]' '{print \$2}'"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
  register: ios_simulator_id
  retries: 3
  delay: 3
  until: ios_simulator_id is not failed

- name: Git checkout
  git:
    repo: "https://github.com/bitrise-io/xcode-test-apps"
    dest: "/opt/bitrise/testapps"
    version: "1.0"

- name: Xcodebuild iOS
  shell: xcodebuild test -project bitrise.xcodeproj -scheme bitrise -destination 'platform=iOS Simulator,id={{ ios_simulator_id.stdout }}'
  args:
    chdir: "/opt/bitrise/testapps/bitrise"

- name: Xcodebuild macOS
  shell: xcodebuild test -project bitrise-mac.xcodeproj -scheme bitrise-mac -destination 'platform=macOS,arch=x86_64'
  args:
    chdir: "/opt/bitrise/testapps/bitrise-mac"
