---

# Steps to take to be able to install Xcode

# Install Homebrew
# This needs a script to run, or directly by curl
- name: run brew installer script
  script: install_brew.sh creates=/usr/local/bin/brew
- name: brew update
  homebrew: update_homebrew=yes upgrade_all=no

# Ruby
- name: brew install rbenv
  homebrew: name=rbenv state=latest
- name: Install ruby {{ default_ruby }}
  shell: bash -l -c "rbenv install --skip-existing {{ default_ruby }}"
  when: is_incremental_setup|default(false) == false
- name: Set ruby {{ default_ruby }} to global
  shell: bash -l -c "rbenv global {{ default_ruby }}"
  when: is_incremental_setup|default(false) == false

# Install deps // fastlane xcode-install
- gem:
    name: fastlane
    state: latest
    executable: "/Users/{{ param_user }}/.rbenv/shims/gem"

- gem:
    name: xcode-install
    state: latest
    executable: "/Users/{{ param_user }}/.rbenv/shims/gem"

# Install Xcode with xcversion
# `xcversion install {{ xcode_version }}`
# - name: Install Xcode
#   shell: bash -l -c "xcversion install {{ xcode_version }}"

# Install simulators in a loop
# xcversion simulators --install={{ item }}
# - name: Install iOS Simulators
#   shell: bash -l -c "xcversion simulators --install='{{ item }}'"
#   loop:
#     - "iOS 12.4"

# Select installed xcode as default
# `xcversion select {{ xcode_version }}
# - name: Set up as default Xcode
#   shell: bash -l -c "xcversion select {{ xcode_version }}"
