---
- name: Run Ruby test
  include_tasks:
    file: ruby_test.yml
  when: ansible_system == "Linux"

- name: Run Ruby install
  include_tasks:
    file: ruby_prod.yml
  when: ansible_system == "Darwin"
